# Generated by Django 5.1.3 on 2024-11-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='scoore',
            new_name='score',
        ),
    ]
